In [139]:
1588455+5555565

7144020

In [140]:
888/5555

0.15985598559855985

My First Class

In [141]:
x=10

In [142]:
print(x)

10


In [143]:
x

10

In [144]:
type(x)

int

In [146]:
y='xx'

In [147]:
y

'xx'

In [148]:
type(y)

str

In [151]:
y1="xx's"

In [152]:
y1

"xx's"

In [153]:
#List

In [154]:
l1=[10,20,30,'xx']

In [155]:
l1

[10, 20, 30, 'xx']

In [156]:
type(l1)

list

In [157]:
l1[0]

10

In [158]:
l1[0]=15

In [159]:
l1

[15, 20, 30, 'xx']

In [161]:
l1[-2]

30

In [162]:
#slicing

In [163]:
l1[1:3]

[20, 30]

In [164]:
l1.append(40)

In [165]:
l1

[15, 20, 30, 'xx', 40]

In [166]:
l1.append([50,60,70])

In [167]:
l1

[15, 20, 30, 'xx', 40, [50, 60, 70]]

In [169]:
l1[-1][1]

60

In [170]:
l1[4]

40

In [171]:
l1.extend(['yy','zz'])

In [172]:
l1

[15, 20, 30, 'xx', 40, [50, 60, 70], 'yy', 'zz']

In [176]:
l1.insert(2,5)

In [177]:
l1

[15, 20, 5, 5, 30, 'xx', 40, [50, 60, 70], 'yy', 'zz']

In [178]:
l1.pop()

'zz'

In [179]:
l1.pop(-1)

'yy'

In [180]:
l1

[15, 20, 5, 5, 30, 'xx', 40, [50, 60, 70]]

In [181]:
del l1

In [182]:
l1

NameError: name 'l1' is not defined

In [ ]:
#Dictionary

In [184]:
dict1={'xx':10,'yy':20,'zz':30}


In [186]:
dict1

{'xx': 10, 'yy': 20, 'zz': 30}

In [187]:
dict1['xx']

10

In [188]:
dict1['xx']=15

In [189]:
dict1

{'xx': 15, 'yy': 20, 'zz': 30}

In [190]:
dict1.keys()

dict_keys(['xx', 'yy', 'zz'])

In [191]:
dict1.values()

dict_values([15, 20, 30])

In [192]:
dict1.items()

dict_items([('xx', 15), ('yy', 20), ('zz', 30)])

In [193]:
#update

In [194]:
dict1.update({'ll':40,'mm':50})

In [195]:
dict1

{'xx': 15, 'yy': 20, 'zz': 30, 'll': 40, 'mm': 50}

In [196]:
dict1.pop('mm')

50

In [197]:
dict1

{'xx': 15, 'yy': 20, 'zz': 30, 'll': 40}

In [198]:
dict1

{'xx': 15, 'yy': 20, 'zz': 30, 'll': 40}

In [201]:
dict1.pop('mm')

KeyError: 'mm'

In [202]:
dict1

{'xx': 15, 'yy': 20, 'zz': 30, 'll': 40}

In [203]:
dict1.pop('yy')

20

In [205]:
dict1.pop('zz','xx')

30

In [206]:
dict1

{'xx': 15, 'll': 40}

In [207]:
dict1.popitem()

('ll', 40)

In [ ]:
#tupple

In [10]:
t=(10,20,30,'xx')

In [7]:
t=()

In [8]:
t

()

In [9]:
type(t)

tuple

In [11]:
t[0]

10

In [12]:
t1=(100, 10, 5, 25, 30, 35)

In [13]:
max(t1)

100

In [14]:
min(t1)

5

In [15]:
t1.count(30)

1

In [ ]:
#set

In [16]:
s1=set(t1) #converting the tuple abve to Set

In [17]:
type(s1)

set

In [18]:
s1

{5, 10, 25, 30, 35, 100}

In [19]:
s1.add(50)

In [20]:
s1

{5, 10, 25, 30, 35, 50, 100}

In [21]:
s1[0] #sets are not indexed

TypeError: 'set' object is not subscriptable

In [22]:
s2=set([10,20,30,40])

In [23]:
s2

{10, 20, 30, 40}

In [25]:
s3=set(['xx', 'yy','zz'])

In [26]:
s3

{'xx', 'yy', 'zz'}

In [27]:
s2=set(['xx','yy','zz','11'])

In [28]:
s1.intersection(s2)

set()

In [29]:
s1.union(s2)

{10, 100, '11', 25, 30, 35, 5, 50, 'xx', 'yy', 'zz'}

In [30]:
s1.issubset(s2)

False

In [31]:
s1.issuperset(s2)

False

In [32]:
s2.issuperset(s1)

False

In [ ]:
#Numpy and Array 

In [35]:
import numpy as np

In [36]:
an_array=np.array([3, 33, 333]) #rank 1 array

In [37]:
an_array

array([  3,  33, 333])

In [38]:
type(an_array)

numpy.ndarray

In [39]:
an_array[0]

3

In [40]:
an_array[1]

33

In [41]:
an_array[1]=55

In [42]:
an_array

array([  3,  55, 333])

In [43]:
an_array.shape

(3,)

In [52]:
an_array1=np.array([[55,60,65,70],[75,80,85,90]])

In [53]:
an_array1

array([[55, 60, 65, 70],
       [75, 80, 85, 90]])

In [54]:
an_array.shape

(3,)

In [138]:
an_array2=np.array([[10,20,30,],[40,50]])

C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_18704\3775560434.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  an_array2=np.array([[10,20,30,],[40,50]])


In [57]:
an_array2

array([list([10, 20, 30]), list([40, 50])], dtype=object)

In [56]:
an_array1

array([[55, 60, 65, 70],
       [75, 80, 85, 90]])

In [58]:
ex1=np.zeros([2,2])  #inbuilt functions - it will be prefilled by zeros

In [59]:
ex1

array([[0., 0.],
       [0., 0.]])

In [60]:
ex2=np.ones([2,2])  #inbuilt functions - it will be prefilled by one

In [61]:
ex2

array([[1., 1.],
       [1., 1.]])

In [63]:
ex3=np.eye(3,3)

In [64]:
ex3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
ex4=np.full((2,2),9.0)

In [69]:
ex4

array([[9., 9.],
       [9., 9.]])

In [72]:
an_array3=np.array([[11,12,13,14,],[15,16,17,18],[19,20,21,22]])

In [73]:
an_array3

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [74]:
an_array3[1]

array([15, 16, 17, 18])

In [78]:
an_array3[1:3]

array([[15, 16, 17, 18],
       [19, 20, 21, 22]])

an_array3[:,1:3]

In [79]:
an_array3[:,1:3]

array([[12, 13],
       [16, 17],
       [20, 21]])

In [80]:
an_array3[:,1:3]

array([[12, 13],
       [16, 17],
       [20, 21]])

In [81]:
an_array3[1:3,]

array([[15, 16, 17, 18],
       [19, 20, 21, 22]])

In [83]:
an_array3

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [82]:
an_array3[:,1:3]

array([[12, 13],
       [16, 17],
       [20, 21]])

In [84]:
an_array4=np.array([[11,12],[15,16],[17,18]])

In [85]:
an_array4

array([[11, 12],
       [15, 16],
       [17, 18]])

In [87]:
filter1=(an_array4>15)

In [89]:
filter1

array([[False, False],
       [False,  True],
       [ True,  True]])

In [90]:
filter2=(an_array4%2==0)

In [91]:
filter2

array([[False,  True],
       [False,  True],
       [False,  True]])

In [92]:
an_array4[filter2]

array([12, 16, 18])

In [93]:
array1=np.array([11,12],dtype=np.float64)

In [94]:
array1

array([11., 12.])

In [98]:
array2=np.array([11.5,12.5],dtype=np.int64)

In [96]:
array2

array([11, 12], dtype=int64)

In [101]:
x=np.array([[111,120],[121,122]])
y=np.array([[550,600],[125,130]])

In [102]:
z=x+y

In [103]:
z

array([[661, 720],
       [246, 252]])

In [108]:
z=np.add(x,y)

In [109]:
z

array([[661, 720],
       [246, 252]])

In [110]:
z1=np.multiply(x,y)

In [111]:
z1

array([[61050, 72000],
       [15125, 15860]])

In [112]:
z2=np.subtract(x,y)

In [113]:
z2

array([[-439, -480],
       [  -4,   -8]])

In [114]:
z3=np.divide(x,y)

In [115]:
z3

array([[0.20181818, 0.2       ],
       [0.968     , 0.93846154]])

In [116]:
filter3=(x>5)

In [117]:
filter3

array([[ True,  True],
       [ True,  True]])

In [118]:
z=x>y

In [119]:
z

array([[False, False],
       [False, False]])

In [123]:
arr=10*np.random.randn(2,5)

In [125]:
arr

array([[ -9.20944965,  -7.05511127, -15.71788229,  -9.01051694,
          4.65774669],
       [ 12.40863558, -19.67910713,   0.48987803,   2.52355441,
          8.51972664]])

In [126]:
print(arr.mean())

-3.207252592665075


In [127]:
print(arr.mean(axis=1)) #axis =1 for row

[-7.26704269  0.85253751]


In [128]:
print(arr.mean(axis=0)) #axis for col

[  1.59959297 -13.3671092   -7.61400213  -3.24348126   6.58873666]


In [130]:
print(arr.sum())

-32.07252592665075


In [131]:
arr.sum()

-32.07252592665075

In [132]:
print(arr.mean())

-3.207252592665075


In [133]:
x1=np.array(['xx','yy','zz'])
x2=np.array(['xx','yy','zz','11'])

In [134]:
np.intersect1d(x1,x2)

array(['xx', 'yy', 'zz'], dtype='<U2')

In [135]:
np.union1d(x1,x2)

array(['11', 'xx', 'yy', 'zz'], dtype='<U2')

In [136]:
np.setdiff1d(x1,x2)

array([], dtype='<U2')

In [137]:
np.setdiff1d(x2,x1)

array(['11'], dtype='<U2')